[package]
name = "crudapi-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.86"
quote = "1.0.15"
darling = "0.13.1"
async-trait = "0.1.52"

[lib]
proc-macro = true
